info: CustomCategory_TestMessageWithoutResponse[711195907]
      Handling message with payload
      {
        "Payload": 10
      }
      (Message ID: test-message-id, Trace ID: test-trace-id)
fail: CustomCategory_TestMessageWithoutResponse[2027292319]
      An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)
      Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages+TestException: test exception
         at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseHandler.Handle(TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line FIXED
         at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler.global::Conqueror.IMessageHandler<Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse,Conqueror.UnitMessageResponse,Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse.IHandler>.Invoke(IHandler handler, TestMessageWithoutResponse message, CancellationToken cancellationToken) in {ProjectDirectory}obj/Debug/net8.0/Conqueror.SourceGenerators/Conqueror.SourceGenerators.Messaging.MessageTypeGenerator/Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponse_ConquerorMessageType.g.cs:line FIXED
         at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line FIXED
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx)

