info: CustomCategory_TestMessageWithComplexPayload[711195907]
      Handling message with payload {"Payload":10,"NestedPayload":{"Payload":11,"Payload2":12}} (Message ID: test-message-id, Trace ID: test-trace-id)
fail: CustomCategory_TestMessageWithComplexPayload[2027292319]
      An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)
      Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages+TestException: test exception
         at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithComplexPayloadHandler.Handle(TestMessageWithComplexPayload message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line 769
         at Conqueror.Messaging.InProcessMessageTransport`2.HandlerInvoker.Send(TMessage message, IServiceProvider serviceProvider, ConquerorContext conquerorContext, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/InProcessMessageTransport.cs:line 40
         at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line 52
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx)

