{"EventId":711195907,"LogLevel":"Information","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessage","Message":"Handling message on in-process sender with payload TestMessage { Payload = 10 } (Message ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling message on in-process sender with payload TestMessage { Payload = 10 } (Message ID: test-message-id, Trace ID: test-trace-id)","TransportTypeName":"in-process","TransportRole":"sender","MessagePayload":"TestMessage { Payload = 10 }","MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling message on {TransportTypeName:l} {TransportRole:l} with payload {@MessagePayload:l} (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
{"EventId":711195907,"LogLevel":"Information","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessage","Message":"Handling message with payload TestMessage { Payload = 10 } (Message ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling message with payload TestMessage { Payload = 10 } (Message ID: test-message-id, Trace ID: test-trace-id)","MessagePayload":"TestMessage { Payload = 10 }","MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling message with payload {@MessagePayload:l} (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
{"EventId":2027292319,"LogLevel":"Error","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessage","Message":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageHandler.Handle(TestMessage message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line FIXED\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line FIXED\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine\u0026 stateMachine)\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx)\n   at Conqueror.Messaging.MessagePipelineRunner\u00602.\u003C\u003Ec__DisplayClass3_2.\u003CExecute\u003Eb__1(TMessage message, CancellationToken token) in {SolutionDirectory}src/Conqueror/Messaging/MessagePipelineRunner.cs:line FIXED","State":{"Message":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling message after {ResponseLatency:0.0000}ms (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
{"EventId":2027292319,"LogLevel":"Error","Category":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessage","Message":"An exception occurred while handling message on in-process sender after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageHandler.Handle(TestMessage message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line FIXED\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line FIXED\n   at Conqueror.Messaging.MessagePipelineRunner\u00602.Execute(IServiceProvider serviceProvider, TMessage initialMessage, IMessageSender\u00602 sender, MessageTransportType transportType, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/MessagePipelineRunner.cs:line FIXED\n   at Conqueror.Messaging.MessageDispatcher\u00602.Dispatch(TMessage message, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/MessageDispatcher.cs:line FIXED\n   at Conqueror.Messaging.MessageHandlerInvoker\u00602.Invoke[TM,TR](TM message, IServiceProvider serviceProvider, String transportTypeName, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Messaging/MessageHandlerInvoker.cs:line FIXED","State":{"Message":"An exception occurred while handling message on in-process sender after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","TransportTypeName":"in-process","TransportRole":"sender","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling message on {TransportTypeName:l} {TransportRole:l} after {ResponseLatency:0.0000}ms (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
